# Generated by Django 5.0.3 on 2024-08-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('specific_gravity', models.FloatField()),
                ('albumin', models.FloatField()),
                ('sugar', models.FloatField()),
                ('red_blood_cells', models.IntegerField()),
                ('pus_cell', models.IntegerField()),
                ('pus_cell_clumps', models.IntegerField()),
                ('bacteria', models.IntegerField()),
                ('blood_glucose_random', models.FloatField()),
                ('blood_urea', models.FloatField()),
                ('serum_creatinine', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('haemoglobin', models.FloatField()),
                ('packed_cell_volume', models.FloatField()),
                ('white_blood_cell_count', models.FloatField()),
                ('red_blood_cell_count', models.FloatField()),
                ('hypertension', models.IntegerField()),
                ('diabetes_mellitus', models.IntegerField()),
                ('coronary_artery_disease', models.IntegerField()),
                ('appetite', models.IntegerField()),
                ('pedal_edema', models.IntegerField()),
                ('anemia', models.IntegerField()),
                ('prediction', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renal_app.profile')),
            ],
        ),
    ]
