# Generated by Django 5.0.3 on 2024-08-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renal_app', '0002_patienttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttest',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
